version: '3'

services:
  grafana:
            build:
                dockerfile: Dockerfile
                context: ./serve/src/grafana/
            image: aegis/grafana
            networks: 
              - aegis
            volumes: 
              - grafana:/var/lib/grafana
            container_name: aegis_grafana
            ports:
              - "3030:3000"

  
networks:
  aegis:
    driver: bridge
volumes:
  grafana_volume:
    driver: local
    external: false


