version: '3'

services:
  node-red:
            build:
                dockerfile: Dockerfile
                context: ./serve/src/node-red/
            image: aegis/node-red
            ports: 
              - "8880:1880"
              - "8883:1883"
            networks: 
              - aegis
            volumes: 
              - nodered:/data
            container_name: aegis_nodered
            environment:
              - NODE_RED_CREDENTIAL_SECRET=my_credential_password
              - TZ=America/Sao_Paulo
            depends_on:
              - db
            restart: always
  db:
            build:
                dockerfile: Dockerfile
                context: ./serve/src/db/
            image: aegis/db
            networks: 
              - aegis
            volumes: 
              - db:/var/lib/postgresql/data
            container_name: aegis_db
            environment:
              - POSTGRES_PASSWORD=P0stgr&s
            restart: always
  pgAdmin:
            image: dpage/pgadmin4:6.9
            container_name: aegis_pgAdmin
            environment:
              - PGADMIN_DEFAULT_USER=aegisAdmin
              - PGADMIN_DEFAULT_EMAIL=aegis@admin.com
              - PGADMIN_DEFAULT_PASSWORD=aegisAdmin
            networks:
              - aegis
            volumes:
              - pgAdmin:/var/lib/pgadmin
            depends_on:
              - db
            ports:
              - "80:80"
            restart: always
  grafana:
            build:
                dockerfile: Dockerfile
                context: ./serve/src/grafana/
            image: aegis/grafana
            networks: 
              - aegis
            volumes: 
              - grafana:/var/lib/grafana
            container_name: aegis_grafana
            ports:
              - "3030:3000"
            depends_on:
              - db
            restart: always

  
networks:
  aegis:
    driver: bridge
    
volumes:
  nodered:
    driver: local
    external: false

  db:
    driver: local
    external: false

  pgAdmin:
    driver: local
    external: false

  grafana:
    driver: local
    external: false


